apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "new-api.fullname" . }}
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end -}}
