apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-bridge.fullname" . }}
  labels:
    {{- include "ai-bridge.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end -}}
